/**
 * Mock-данные для демонстрации без подключения Supabase.
 * Используются когда NEXT_PUBLIC_SUPABASE_URL не задан.
 */

import type { IProjectCard } from '@/types/project';

/** Mock-проекты */
export const MOCK_PROJECTS: IProjectCard[] = [
  {
    id: '1',
    title: 'Разработка интернет-магазина на Next.js + Supabase',
    slug: 'razrabotka-internet-magazina-nextjs',
    category: 'web-development',
    description:
      'Нужен опытный full-stack разработчик для создания современного интернет-магазина электроники. Стек: Next.js 15, TypeScript, Supabase, Tailwind CSS. Требуется каталог товаров, корзина, оплата через Stripe, личный кабинет, админ-панель. Адаптивный дизайн по готовым макетам в Figma.',
    skills: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'Stripe'],
    budgetType: 'fixed',
    budgetMin: 3000,
    budgetMax: 5000,
    status: 'open',
    proposalCount: 12,
    clientName: 'Андрей К.',
    clientAvatarUrl: undefined,
    clientRating: 4.8,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Мобильное приложение для фитнес-трекинга (React Native)',
    slug: 'mobilnoe-prilozhenie-fitness',
    category: 'mobile-development',
    description:
      'Разработка кроссплатформенного мобильного приложения для трекинга тренировок. Функционал: отслеживание упражнений, статистика, социальные функции, уведомления, интеграция с Apple Health / Google Fit. Дизайн уже готов.',
    skills: ['React Native', 'TypeScript', 'Firebase', 'REST API'],
    budgetType: 'fixed',
    budgetMin: 5000,
    budgetMax: 8000,
    status: 'open',
    proposalCount: 7,
    clientName: 'ФитТех ООО',
    clientRating: 4.5,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Редизайн лендинга SaaS-продукта',
    slug: 'redizajn-lendinga-saas',
    category: 'design',
    description:
      'Нужен UI/UX дизайнер для полного редизайна лендинга нашего SaaS-продукта (CRM для малого бизнеса). Включает: исследование конкурентов, wireframes, hi-fi макеты в Figma, адаптив для мобильных. Цель — повысить конверсию с 2% до 5%.',
    skills: ['Figma', 'UI/UX', 'Web Design', 'Prototyping'],
    budgetType: 'fixed',
    budgetMin: 1500,
    budgetMax: 2500,
    status: 'open',
    proposalCount: 18,
    clientName: 'Мария С.',
    clientRating: 4.9,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Бэкенд для маркетплейса на Node.js + PostgreSQL',
    slug: 'backend-marketplace-nodejs',
    category: 'web-development',
    description:
      'Нужен Backend-разработчик для создания API маркетплейса услуг. REST API + WebSocket для чата. Auth, RBAC, платежи, поиск ElasticSearch. Микросервисная архитектура, Docker, CI/CD. Тесты обязательны.',
    skills: ['Node.js', 'PostgreSQL', 'Docker', 'Redis', 'ElasticSearch'],
    budgetType: 'hourly',
    budgetMin: 35,
    budgetMax: 55,
    status: 'open',
    proposalCount: 5,
    clientName: 'StartupHub',
    clientRating: 4.7,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Telegram-бот для автоматизации продаж',
    slug: 'telegram-bot-prodazhi',
    category: 'web-development',
    description:
      'Разработка Telegram-бота для автоматизации продаж курсов. Функционал: каталог курсов, оплата через ЮKassa, выдача доступа, рассылки, статистика, интеграция с CRM. Python + aiogram.',
    skills: ['Python', 'Telegram API', 'PostgreSQL', 'aiogram'],
    budgetType: 'fixed',
    budgetMin: 800,
    budgetMax: 1500,
    status: 'open',
    proposalCount: 22,
    clientName: 'Олег В.',
    clientRating: 4.3,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'DevOps: настройка CI/CD и инфраструктуры на AWS',
    slug: 'devops-cicd-aws',
    category: 'web-development',
    description:
      'Настройка инфраструктуры для стартапа на AWS. Terraform, ECS/Fargate, RDS, S3, CloudFront, GitHub Actions CI/CD. Мониторинг: CloudWatch + Grafana. Staging + Production окружения.',
    skills: ['AWS', 'Terraform', 'Docker', 'GitHub Actions', 'Grafana'],
    budgetType: 'fixed',
    budgetMin: 2000,
    budgetMax: 3500,
    status: 'open',
    proposalCount: 3,
    clientName: 'TechVenture',
    clientRating: 5.0,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

/** Mock-фрилансеры */
export const MOCK_FREELANCERS = [
  {
    id: '101',
    name: 'Алексей Петров',
    title: 'Senior Frontend Developer (React / Next.js)',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'GraphQL', 'Node.js'],
    hourlyRate: 45,
    rating: 4.9,
    reviewCount: 47,
    completedProjects: 38,
    availability: 'available',
    country: 'Россия',
    city: 'Москва',
    isOnline: true,
  },
  {
    id: '102',
    name: 'Екатерина Сидорова',
    title: 'UI/UX Designer & Product Designer',
    skills: ['Figma', 'UI/UX', 'Prototyping', 'Web Design', 'Design Systems'],
    hourlyRate: 40,
    rating: 5.0,
    reviewCount: 63,
    completedProjects: 52,
    availability: 'available',
    country: 'Беларусь',
    city: 'Минск',
    isOnline: true,
  },
  {
    id: '103',
    name: 'Дмитрий Козлов',
    title: 'Full-Stack Developer (Node.js / React)',
    skills: ['Node.js', 'React', 'PostgreSQL', 'Docker', 'AWS', 'TypeScript'],
    hourlyRate: 50,
    rating: 4.8,
    reviewCount: 31,
    completedProjects: 27,
    availability: 'partially_busy',
    country: 'Украина',
    city: 'Киев',
    isOnline: false,
  },
  {
    id: '104',
    name: 'Анна Морозова',
    title: 'Mobile Developer (React Native / Flutter)',
    skills: ['React Native', 'Flutter', 'TypeScript', 'Firebase', 'iOS', 'Android'],
    hourlyRate: 42,
    rating: 4.7,
    reviewCount: 22,
    completedProjects: 19,
    availability: 'available',
    country: 'Россия',
    city: 'Санкт-Петербург',
    isOnline: true,
  },
  {
    id: '105',
    name: 'Иван Новиков',
    title: 'DevOps Engineer & Cloud Architect',
    skills: ['AWS', 'Terraform', 'Kubernetes', 'Docker', 'CI/CD', 'Linux'],
    hourlyRate: 55,
    rating: 4.9,
    reviewCount: 18,
    completedProjects: 15,
    availability: 'available',
    country: 'Казахстан',
    city: 'Алматы',
    isOnline: false,
  },
  {
    id: '106',
    name: 'Ольга Васильева',
    title: 'Backend Developer (Python / Django)',
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis', 'Celery', 'REST API'],
    hourlyRate: 38,
    rating: 4.6,
    reviewCount: 29,
    completedProjects: 24,
    availability: 'available',
    country: 'Россия',
    city: 'Новосибирск',
    isOnline: true,
  },
  {
    id: '107',
    name: 'Максим Волков',
    title: 'Blockchain & Smart Contract Developer',
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'React', 'TypeScript', 'Hardhat'],
    hourlyRate: 65,
    rating: 4.8,
    reviewCount: 12,
    completedProjects: 10,
    availability: 'partially_busy',
    country: 'Грузия',
    city: 'Тбилиси',
    isOnline: false,
  },
  {
    id: '108',
    name: 'Наталья Кузнецова',
    title: 'QA Engineer & Test Automation',
    skills: ['Playwright', 'Cypress', 'Jest', 'API Testing', 'Selenium', 'TypeScript'],
    hourlyRate: 32,
    rating: 4.9,
    reviewCount: 35,
    completedProjects: 30,
    availability: 'available',
    country: 'Беларусь',
    city: 'Гомель',
    isOnline: true,
  },
  {
    id: '109',
    name: 'Артём Лебедев',
    title: 'Data Scientist & ML Engineer',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Pandas', 'SQL', 'MLOps'],
    hourlyRate: 48,
    rating: 4.7,
    reviewCount: 14,
    completedProjects: 11,
    availability: 'available',
    country: 'Россия',
    city: 'Екатеринбург',
    isOnline: false,
  },
];
